/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jlox;

import org.junit.Test;
import static org.junit.Assert.*;

public class LoxTest {
    @Test
    public void appHasAGreeting() {
        Lox classUnderTest = new Lox();
        assertNotNull("(1 + 1) == (2)", 1 + 1);
    }
}
